// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Archive(arg1) {
  return window['go']['desktop']['App']['Archive'](arg1);
}

export function AskAI(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['AskAI'](arg1, arg2, arg3);
}

export function Confirm(arg1, arg2) {
  return window['go']['desktop']['App']['Confirm'](arg1, arg2);
}

export function Connect() {
  return window['go']['desktop']['App']['Connect']();
}

export function Delete(arg1) {
  return window['go']['desktop']['App']['Delete'](arg1);
}

export function DeleteDraft(arg1) {
  return window['go']['desktop']['App']['DeleteDraft'](arg1);
}

export function Disconnect() {
  return window['go']['desktop']['App']['Disconnect']();
}

export function GetAIProviders() {
  return window['go']['desktop']['App']['GetAIProviders']();
}

export function GetAccounts() {
  return window['go']['desktop']['App']['GetAccounts']();
}

export function GetAnalytics(arg1) {
  return window['go']['desktop']['App']['GetAnalytics'](arg1);
}

export function GetAnalyticsOverview() {
  return window['go']['desktop']['App']['GetAnalyticsOverview']();
}

export function GetAppInfo() {
  return window['go']['desktop']['App']['GetAppInfo']();
}

export function GetConnectionStatus() {
  return window['go']['desktop']['App']['GetConnectionStatus']();
}

export function GetCurrentAccount() {
  return window['go']['desktop']['App']['GetCurrentAccount']();
}

export function GetCurrentFolder() {
  return window['go']['desktop']['App']['GetCurrentFolder']();
}

export function GetDraft(arg1) {
  return window['go']['desktop']['App']['GetDraft'](arg1);
}

export function GetEmail(arg1) {
  return window['go']['desktop']['App']['GetEmail'](arg1);
}

export function GetEmailByUID(arg1) {
  return window['go']['desktop']['App']['GetEmailByUID'](arg1);
}

export function GetEmails(arg1, arg2) {
  return window['go']['desktop']['App']['GetEmails'](arg1, arg2);
}

export function GetFolders() {
  return window['go']['desktop']['App']['GetFolders']();
}

export function GetSignature() {
  return window['go']['desktop']['App']['GetSignature']();
}

export function GetTopSenders(arg1, arg2) {
  return window['go']['desktop']['App']['GetTopSenders'](arg1, arg2);
}

export function IsConnected() {
  return window['go']['desktop']['App']['IsConnected']();
}

export function IsReady() {
  return window['go']['desktop']['App']['IsReady']();
}

export function ListDrafts() {
  return window['go']['desktop']['App']['ListDrafts']();
}

export function MarkAsRead(arg1, arg2) {
  return window['go']['desktop']['App']['MarkAsRead'](arg1, arg2);
}

export function MarkAsStarred(arg1, arg2) {
  return window['go']['desktop']['App']['MarkAsStarred'](arg1, arg2);
}

export function MoveToFolder(arg1, arg2) {
  return window['go']['desktop']['App']['MoveToFolder'](arg1, arg2);
}

export function NeedsOAuth2Auth() {
  return window['go']['desktop']['App']['NeedsOAuth2Auth']();
}

export function NeedsSetup() {
  return window['go']['desktop']['App']['NeedsSetup']();
}

export function OpenURL(arg1) {
  return window['go']['desktop']['App']['OpenURL'](arg1);
}

export function SaveDraft(arg1) {
  return window['go']['desktop']['App']['SaveDraft'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['desktop']['App']['Search'](arg1, arg2);
}

export function SearchInFolder(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SearchInFolder'](arg1, arg2, arg3);
}

export function SelectFolder(arg1) {
  return window['go']['desktop']['App']['SelectFolder'](arg1);
}

export function SendDraft(arg1) {
  return window['go']['desktop']['App']['SendDraft'](arg1);
}

export function SendEmail(arg1) {
  return window['go']['desktop']['App']['SendEmail'](arg1);
}

export function ShowError(arg1, arg2) {
  return window['go']['desktop']['App']['ShowError'](arg1, arg2);
}

export function ShowInfo(arg1, arg2) {
  return window['go']['desktop']['App']['ShowInfo'](arg1, arg2);
}

export function StartOAuth2Auth() {
  return window['go']['desktop']['App']['StartOAuth2Auth']();
}

export function SwitchToTerminal() {
  return window['go']['desktop']['App']['SwitchToTerminal']();
}

export function SyncCurrentFolder() {
  return window['go']['desktop']['App']['SyncCurrentFolder']();
}

export function SyncFolder(arg1) {
  return window['go']['desktop']['App']['SyncFolder'](arg1);
}
