// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function Archive(arg1:number):Promise<void>;

export function AskAI(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AuthenticateBasecamp():Promise<Array<desktop.BasecampAccountDTO>>;

export function BatchArchive(arg1:Array<number>):Promise<void>;

export function BatchDelete(arg1:Array<number>):Promise<void>;

export function BatchMarkRead(arg1:Array<number>,arg2:boolean):Promise<void>;

export function BatchStar(arg1:Array<number>,arg2:boolean):Promise<void>;

export function CanRedo():Promise<boolean>;

export function CanUndo():Promise<boolean>;

export function CancelThreadSync():Promise<void>;

export function CompleteBasecampTodo(arg1:number,arg2:number):Promise<void>;

export function Confirm(arg1:string,arg2:string):Promise<boolean>;

export function Connect():Promise<void>;

export function ConnectBasecamp():Promise<void>;

export function CreateBasecampTodo(arg1:desktop.BasecampTodoInputDTO):Promise<desktop.BasecampTodoDTO>;

export function CreateCalendarEvent(arg1:desktop.CalendarEventInputDTO):Promise<desktop.CalendarEventDTO>;

export function CreateFollowUpEvent(arg1:number,arg2:string,arg3:string):Promise<desktop.CalendarEventDTO>;

export function CreateTask(arg1:desktop.TaskInputDTO):Promise<desktop.TaskDTO>;

export function Delete(arg1:number):Promise<void>;

export function DeleteCalendarEvent(arg1:number):Promise<void>;

export function DeleteDraft(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function Disconnect():Promise<void>;

export function DisconnectBasecamp():Promise<void>;

export function DownloadAttachment(arg1:number):Promise<string>;

export function ExtractActions(arg1:number):Promise<Array<string>>;

export function GetAIProviders():Promise<Array<Record<string, any>>>;

export function GetAccounts():Promise<Array<desktop.AccountDTO>>;

export function GetAnalytics(arg1:string):Promise<desktop.AnalyticsResultDTO>;

export function GetAnalyticsOverview():Promise<desktop.AnalyticsOverviewDTO>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetAttachments(arg1:number):Promise<Array<desktop.AttachmentDTO>>;

export function GetAvailableFolders():Promise<Array<desktop.AvailableFolderDTO>>;

export function GetBasecampConfig():Promise<desktop.BasecampConfigDTO>;

export function GetBasecampMessages(arg1:number,arg2:number):Promise<Array<desktop.BasecampMessageDTO>>;

export function GetBasecampPeople():Promise<Array<desktop.BasecampPersonDTO>>;

export function GetBasecampProjects():Promise<Array<desktop.BasecampProjectDTO>>;

export function GetBasecampTodoLists(arg1:number):Promise<Array<desktop.BasecampTodoListDTO>>;

export function GetBasecampTodos(arg1:number,arg2:number):Promise<Array<desktop.BasecampTodoDTO>>;

export function GetCachedSummary(arg1:number):Promise<desktop.SummaryResult>;

export function GetCalendarEventCounts():Promise<desktop.CalendarEventCountsDTO>;

export function GetCalendarEvents():Promise<Array<desktop.CalendarEventDTO>>;

export function GetCalendarEventsForWeek(arg1:string):Promise<Array<desktop.CalendarEventDTO>>;

export function GetConnectionStatus():Promise<desktop.ConnectionStatus>;

export function GetContactSyncStatus():Promise<desktop.ContactSyncStatusDTO>;

export function GetCurrentAccount():Promise<desktop.AccountDTO>;

export function GetCurrentFolder():Promise<string>;

export function GetDraft(arg1:number):Promise<desktop.DraftDTO>;

export function GetEmail(arg1:number):Promise<desktop.EmailDetailDTO>;

export function GetEmailByID(arg1:number):Promise<desktop.EmailDTO>;

export function GetEmailByUID(arg1:number):Promise<desktop.EmailDetailDTO>;

export function GetEmails(arg1:string,arg2:number):Promise<Array<desktop.EmailDTO>>;

export function GetEmailsThreaded(arg1:string,arg2:number):Promise<Array<desktop.EmailDTO>>;

export function GetFolders():Promise<Array<desktop.FolderDTO>>;

export function GetGoogleCalendarEvents(arg1:string,arg2:string):Promise<Array<desktop.GoogleEventDTO>>;

export function GetPendingTasks():Promise<Array<desktop.TaskDTO>>;

export function GetSettings():Promise<desktop.SettingsDTO>;

export function GetSignature():Promise<string>;

export function GetTaskCounts():Promise<desktop.TaskCountsDTO>;

export function GetTasks():Promise<Array<desktop.TaskDTO>>;

export function GetThread(arg1:number):Promise<desktop.ThreadDTO>;

export function GetThreadByID(arg1:string):Promise<desktop.ThreadDTO>;

export function GetThreadMessageCount(arg1:number):Promise<number>;

export function GetThreadSummary(arg1:string):Promise<desktop.ThreadSummaryDTO>;

export function GetTopContacts(arg1:number):Promise<Array<desktop.ContactDTO>>;

export function GetTopSenders(arg1:number,arg2:string):Promise<Array<desktop.SenderStatsDTO>>;

export function GetUpcomingCalendarEvents(arg1:number):Promise<Array<desktop.CalendarEventDTO>>;

export function InvalidateSummary(arg1:number):Promise<void>;

export function IsBasecampConnected():Promise<boolean>;

export function IsConnected():Promise<boolean>;

export function IsGoogleCalendarConnected():Promise<boolean>;

export function IsReady():Promise<boolean>;

export function ListDrafts():Promise<Array<desktop.DraftDTO>>;

export function ListGoogleCalendars():Promise<Array<desktop.GoogleCalendarDTO>>;

export function MarkAsRead(arg1:number,arg2:boolean):Promise<void>;

export function MarkAsStarred(arg1:number,arg2:boolean):Promise<void>;

export function MarkThreadAsRead(arg1:string):Promise<void>;

export function MarkThreadAsUnread(arg1:string):Promise<void>;

export function MoveToFolder(arg1:number,arg2:string):Promise<void>;

export function NeedsOAuth2Auth():Promise<boolean>;

export function NeedsSetup():Promise<boolean>;

export function OpenAttachment(arg1:number,arg2:string):Promise<void>;

export function OpenAttachmentByPart(arg1:number,arg2:string,arg3:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PostBasecampMessage(arg1:number,arg2:string,arg3:string):Promise<desktop.BasecampMessageDTO>;

export function Redo():Promise<desktop.UndoResult>;

export function SaveAttachment(arg1:number,arg2:string):Promise<void>;

export function SaveAttachmentByPart(arg1:number,arg2:string,arg3:string):Promise<string>;

export function SaveAttachmentDialog(arg1:number,arg2:string):Promise<string>;

export function SaveBasecampConfig(arg1:desktop.BasecampConfigDTO):Promise<void>;

export function SaveDraft(arg1:desktop.DraftDTO):Promise<number>;

export function SaveSettings(arg1:desktop.SettingsDTO):Promise<void>;

export function Search(arg1:string,arg2:number):Promise<desktop.SearchResultDTO>;

export function SearchContacts(arg1:string,arg2:number):Promise<Array<desktop.ContactDTO>>;

export function SearchInFolder(arg1:string,arg2:string,arg3:number):Promise<desktop.SearchResultDTO>;

export function SelectBasecampAccount(arg1:number):Promise<void>;

export function SelectFolder(arg1:string):Promise<desktop.FolderDTO>;

export function SendDraft(arg1:number):Promise<desktop.SendResult>;

export function SendEmail(arg1:desktop.SendRequest):Promise<desktop.SendResult>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowInfo(arg1:string,arg2:string):Promise<void>;

export function StartOAuth2Auth():Promise<void>;

export function SummarizeEmail(arg1:number):Promise<string>;

export function SummarizeEmailWithStyle(arg1:number,arg2:string):Promise<desktop.SummaryResult>;

export function SummarizeThread(arg1:number):Promise<string>;

export function SummarizeThreadDetailed(arg1:number):Promise<desktop.ThreadSummaryResult>;

export function SwitchToTerminal():Promise<void>;

export function SyncContacts(arg1:boolean):Promise<void>;

export function SyncCurrentFolder():Promise<desktop.SyncResultDTO>;

export function SyncEssentialFolders():Promise<Array<desktop.SyncResultDTO>>;

export function SyncFolder(arg1:string):Promise<desktop.SyncResultDTO>;

export function SyncFromGoogleCalendar(arg1:string):Promise<number>;

export function SyncTasksToCalendar():Promise<void>;

export function SyncThreadsFromGmail():Promise<number>;

export function ToggleCalendarEventComplete(arg1:number):Promise<boolean>;

export function ToggleTaskComplete(arg1:number):Promise<boolean>;

export function UncompleteBasecampTodo(arg1:number,arg2:number):Promise<void>;

export function Undo():Promise<desktop.UndoResult>;

export function UpdateBasecampTodo(arg1:desktop.BasecampTodoInputDTO):Promise<desktop.BasecampTodoDTO>;

export function UpdateCalendarEvent(arg1:desktop.CalendarEventInputDTO):Promise<desktop.CalendarEventDTO>;

export function UpdateTask(arg1:desktop.TaskInputDTO):Promise<desktop.TaskDTO>;
