// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function Archive(arg1:number):Promise<void>;

export function AskAI(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Confirm(arg1:string,arg2:string):Promise<boolean>;

export function Connect():Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function DeleteDraft(arg1:number):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAIProviders():Promise<Array<Record<string, any>>>;

export function GetAccounts():Promise<Array<desktop.AccountDTO>>;

export function GetAnalytics(arg1:string):Promise<desktop.AnalyticsResultDTO>;

export function GetAnalyticsOverview():Promise<desktop.AnalyticsOverviewDTO>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetConnectionStatus():Promise<desktop.ConnectionStatus>;

export function GetCurrentAccount():Promise<desktop.AccountDTO>;

export function GetCurrentFolder():Promise<string>;

export function GetDraft(arg1:number):Promise<desktop.DraftDTO>;

export function GetEmail(arg1:number):Promise<desktop.EmailDetailDTO>;

export function GetEmailByUID(arg1:number):Promise<desktop.EmailDetailDTO>;

export function GetEmails(arg1:string,arg2:number):Promise<Array<desktop.EmailDTO>>;

export function GetFolders():Promise<Array<desktop.FolderDTO>>;

export function GetSignature():Promise<string>;

export function GetTopSenders(arg1:number,arg2:string):Promise<Array<desktop.SenderStatsDTO>>;

export function IsConnected():Promise<boolean>;

export function IsReady():Promise<boolean>;

export function ListDrafts():Promise<Array<desktop.DraftDTO>>;

export function MarkAsRead(arg1:number,arg2:boolean):Promise<void>;

export function MarkAsStarred(arg1:number,arg2:boolean):Promise<void>;

export function MoveToFolder(arg1:number,arg2:string):Promise<void>;

export function NeedsOAuth2Auth():Promise<boolean>;

export function NeedsSetup():Promise<boolean>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveDraft(arg1:desktop.DraftDTO):Promise<number>;

export function Search(arg1:string,arg2:number):Promise<desktop.SearchResultDTO>;

export function SearchInFolder(arg1:string,arg2:string,arg3:number):Promise<desktop.SearchResultDTO>;

export function SelectFolder(arg1:string):Promise<desktop.FolderDTO>;

export function SendDraft(arg1:number):Promise<desktop.SendResult>;

export function SendEmail(arg1:desktop.SendRequest):Promise<desktop.SendResult>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowInfo(arg1:string,arg2:string):Promise<void>;

export function StartOAuth2Auth():Promise<void>;

export function SwitchToTerminal():Promise<void>;

export function SyncCurrentFolder():Promise<void>;

export function SyncFolder(arg1:string):Promise<void>;
