// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main Wails application struct
 * All public methods are exposed to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Archive archives an email
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Archive(id) {
    return $Call.ByID(1798621252, id);
}

/**
 * AskAI sends a question to a CLI-based AI provider
 * @param {string} provider
 * @param {string} question
 * @param {string} emailContextJSON
 * @returns {$CancellablePromise<string>}
 */
export function AskAI(provider, question, emailContextJSON) {
    return $Call.ByID(3348469381, provider, question, emailContextJSON);
}

/**
 * AuthenticateBasecamp starts the OAuth2 flow for Basecamp
 * @returns {$CancellablePromise<$models.BasecampAccountDTO[]>}
 */
export function AuthenticateBasecamp() {
    return $Call.ByID(1381962975).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * BatchArchive archives multiple emails
 * @param {number[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function BatchArchive(ids) {
    return $Call.ByID(2251433336, ids);
}

/**
 * BatchDelete deletes multiple emails
 * @param {number[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function BatchDelete(ids) {
    return $Call.ByID(3935792093, ids);
}

/**
 * BatchMarkRead marks multiple emails as read or unread
 * @param {number[]} ids
 * @param {boolean} read
 * @returns {$CancellablePromise<void>}
 */
export function BatchMarkRead(ids, read) {
    return $Call.ByID(3259389007, ids, read);
}

/**
 * BatchStar stars or unstars multiple emails
 * @param {number[]} ids
 * @param {boolean} starred
 * @returns {$CancellablePromise<void>}
 */
export function BatchStar(ids, starred) {
    return $Call.ByID(2912152042, ids, starred);
}

/**
 * CanRedo returns whether redo is available
 * @returns {$CancellablePromise<boolean>}
 */
export function CanRedo() {
    return $Call.ByID(344051596);
}

/**
 * CanUndo returns whether undo is available
 * @returns {$CancellablePromise<boolean>}
 */
export function CanUndo() {
    return $Call.ByID(2863449850);
}

/**
 * CancelThreadSync cancels an ongoing thread sync operation
 * @returns {$CancellablePromise<void>}
 */
export function CancelThreadSync() {
    return $Call.ByID(2283044599);
}

/**
 * CompleteBasecampTodo marks a todo as completed
 * @param {number} projectID
 * @param {number} todoID
 * @returns {$CancellablePromise<void>}
 */
export function CompleteBasecampTodo(projectID, todoID) {
    return $Call.ByID(2624893973, projectID, todoID);
}

/**
 * Confirm shows a confirmation dialog
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<boolean>}
 */
export function Confirm(title, message) {
    return $Call.ByID(1136421110, title, message);
}

/**
 * Connect connects to the email server
 * @returns {$CancellablePromise<void>}
 */
export function Connect() {
    return $Call.ByID(2210152676);
}

/**
 * ConnectBasecamp connects to Basecamp using saved credentials
 * @returns {$CancellablePromise<void>}
 */
export function ConnectBasecamp() {
    return $Call.ByID(3904885768);
}

/**
 * CreateBasecampTodo creates a new todo
 * @param {$models.BasecampTodoInputDTO} input
 * @returns {$CancellablePromise<$models.BasecampTodoDTO | null>}
 */
export function CreateBasecampTodo(input) {
    return $Call.ByID(481443042, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CreateCalendarEvent creates a new calendar event
 * @param {$models.CalendarEventInputDTO} input
 * @returns {$CancellablePromise<$models.CalendarEventDTO | null>}
 */
export function CreateCalendarEvent(input) {
    return $Call.ByID(840040620, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CreateFollowUpEvent creates a follow-up event for an email
 * @param {number} emailID
 * @param {string} followUpDate
 * @param {string} title
 * @returns {$CancellablePromise<$models.CalendarEventDTO | null>}
 */
export function CreateFollowUpEvent(emailID, followUpDate, title) {
    return $Call.ByID(2416483654, emailID, followUpDate, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CreateTask creates a new task
 * @param {$models.TaskInputDTO} input
 * @returns {$CancellablePromise<$models.TaskDTO | null>}
 */
export function CreateTask(input) {
    return $Call.ByID(1279755455, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Delete moves an email to trash
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(909015409, id);
}

/**
 * DeleteCalendarEvent deletes a calendar event
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCalendarEvent(id) {
    return $Call.ByID(61095625, id);
}

/**
 * DeleteDraft deletes a draft
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDraft(id) {
    return $Call.ByID(3232685528, id);
}

/**
 * DeleteTask removes a task
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTask(id) {
    return $Call.ByID(1461318976, id);
}

/**
 * Disconnect disconnects from the email server
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(897418776);
}

/**
 * DisconnectBasecamp disconnects from Basecamp
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectBasecamp() {
    return $Call.ByID(904312700);
}

/**
 * DownloadAttachment downloads an attachment and returns base64-encoded content
 * @param {number} attachmentID
 * @returns {$CancellablePromise<string>}
 */
export function DownloadAttachment(attachmentID) {
    return $Call.ByID(816845483, attachmentID);
}

/**
 * ExtractActions extracts action items from an email using AI
 * @param {number} emailID
 * @returns {$CancellablePromise<string[]>}
 */
export function ExtractActions(emailID) {
    return $Call.ByID(1801724718, emailID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetAIProviders returns available AI providers and their status
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function GetAIProviders() {
    return $Call.ByID(1980065290).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetAccounts returns all configured accounts
 * @returns {$CancellablePromise<$models.AccountDTO[]>}
 */
export function GetAccounts() {
    return $Call.ByID(3114013642).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetAnalytics returns comprehensive analytics for a time period
 * @param {string} period
 * @returns {$CancellablePromise<$models.AnalyticsResultDTO | null>}
 */
export function GetAnalytics(period) {
    return $Call.ByID(3756502490, period).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetAnalyticsOverview returns basic email statistics
 * @returns {$CancellablePromise<$models.AnalyticsOverviewDTO | null>}
 */
export function GetAnalyticsOverview() {
    return $Call.ByID(625079705).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetAppInfo returns basic app information
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetAppInfo() {
    return $Call.ByID(4151718217).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetAttachments returns all attachments for an email
 * @param {number} emailID
 * @returns {$CancellablePromise<$models.AttachmentDTO[]>}
 */
export function GetAttachments(emailID) {
    return $Call.ByID(1201504116, emailID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetAvailableFolders returns all folders with their sync selection status
 * @returns {$CancellablePromise<$models.AvailableFolderDTO[]>}
 */
export function GetAvailableFolders() {
    return $Call.ByID(2693171094).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * GetBasecampConfig returns the current Basecamp configuration
 * @returns {$CancellablePromise<$models.BasecampConfigDTO | null>}
 */
export function GetBasecampConfig() {
    return $Call.ByID(2347466268).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetBasecampMessages returns messages for a project
 * @param {number} projectID
 * @param {number} limit
 * @returns {$CancellablePromise<$models.BasecampMessageDTO[]>}
 */
export function GetBasecampMessages(projectID, limit) {
    return $Call.ByID(2894056446, projectID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * GetBasecampPeople returns all people in the Basecamp account
 * @returns {$CancellablePromise<$models.BasecampPersonDTO[]>}
 */
export function GetBasecampPeople() {
    return $Call.ByID(240922353).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetBasecampProjects returns all Basecamp projects
 * @returns {$CancellablePromise<$models.BasecampProjectDTO[]>}
 */
export function GetBasecampProjects() {
    return $Call.ByID(2061393664).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * GetBasecampTodoLists returns todo lists for a project
 * @param {number} projectID
 * @returns {$CancellablePromise<$models.BasecampTodoListDTO[]>}
 */
export function GetBasecampTodoLists(projectID) {
    return $Call.ByID(1522694647, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * GetBasecampTodos returns todos for a todo list
 * @param {number} projectID
 * @param {number} todoListID
 * @returns {$CancellablePromise<$models.BasecampTodoDTO[]>}
 */
export function GetBasecampTodos(projectID, todoListID) {
    return $Call.ByID(1091816835, projectID, todoListID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetCachedSummary retrieves a cached summary if exists
 * @param {number} emailID
 * @returns {$CancellablePromise<$models.SummaryResult | null>}
 */
export function GetCachedSummary(emailID) {
    return $Call.ByID(4212746916, emailID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * GetCalendarEventCounts returns calendar event statistics
 * @returns {$CancellablePromise<$models.CalendarEventCountsDTO | null>}
 */
export function GetCalendarEventCounts() {
    return $Call.ByID(278987648).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * GetCalendarEvents returns all calendar events for the current account
 * @returns {$CancellablePromise<$models.CalendarEventDTO[]>}
 */
export function GetCalendarEvents() {
    return $Call.ByID(2115845709).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * GetCalendarEventsForWeek returns events for a specific week
 * @param {string} weekStartDate
 * @returns {$CancellablePromise<$models.CalendarEventDTO[]>}
 */
export function GetCalendarEventsForWeek(weekStartDate) {
    return $Call.ByID(184983220, weekStartDate).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * GetConnectionStatus returns current connection status
 * @returns {$CancellablePromise<$models.ConnectionStatus>}
 */
export function GetConnectionStatus() {
    return $Call.ByID(3331918360).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * GetContactSyncStatus returns the current contact sync status
 * @returns {$CancellablePromise<$models.ContactSyncStatusDTO | null>}
 */
export function GetContactSyncStatus() {
    return $Call.ByID(1640639859).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * GetCurrentAccount returns the current account
 * @returns {$CancellablePromise<$models.AccountDTO | null>}
 */
export function GetCurrentAccount() {
    return $Call.ByID(3839071958).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * GetCurrentFolder returns the currently selected folder name
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentFolder() {
    return $Call.ByID(2422784823);
}

/**
 * GetDraft returns a draft by ID
 * @param {number} id
 * @returns {$CancellablePromise<$models.DraftDTO | null>}
 */
export function GetDraft(id) {
    return $Call.ByID(363054129, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * GetEmail returns full email details by ID
 * @param {number} id
 * @returns {$CancellablePromise<$models.EmailDetailDTO | null>}
 */
export function GetEmail(id) {
    return $Call.ByID(3869035390, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * GetEmailByID returns email summary (EmailDTO) by ID for adding to email list
 * This is used when selecting an email from search results that isn't in the current list
 * @param {number} id
 * @returns {$CancellablePromise<$models.EmailDTO | null>}
 */
export function GetEmailByID(id) {
    return $Call.ByID(324946298, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * GetEmailByUID returns email by UID in current folder
 * @param {number} uid
 * @returns {$CancellablePromise<$models.EmailDetailDTO | null>}
 */
export function GetEmailByUID(uid) {
    return $Call.ByID(2419984347, uid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * GetEmails returns emails from a folder
 * @param {string} folder
 * @param {number} limit
 * @returns {$CancellablePromise<$models.EmailDTO[]>}
 */
export function GetEmails(folder, limit) {
    return $Call.ByID(366191991, folder, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * GetEmailsThreaded returns emails from a folder grouped by thread (only latest email per thread with thread count)
 * @param {string} folder
 * @param {number} limit
 * @returns {$CancellablePromise<$models.EmailDTO[]>}
 */
export function GetEmailsThreaded(folder, limit) {
    return $Call.ByID(3552307606, folder, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * GetFolders returns all mail folders
 * @returns {$CancellablePromise<$models.FolderDTO[]>}
 */
export function GetFolders() {
    return $Call.ByID(581531883).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType50($result);
    }));
}

/**
 * GetGoogleCalendarEvents returns events from Google Calendar for a week
 * @param {string} calendarID
 * @param {string} weekStartDate
 * @returns {$CancellablePromise<$models.GoogleEventDTO[]>}
 */
export function GetGoogleCalendarEvents(calendarID, weekStartDate) {
    return $Call.ByID(2744884710, calendarID, weekStartDate).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType52($result);
    }));
}

/**
 * GetPendingTasks returns only incomplete tasks
 * @returns {$CancellablePromise<$models.TaskDTO[]>}
 */
export function GetPendingTasks() {
    return $Call.ByID(2414849245).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * GetSettings returns all application settings
 * @returns {$CancellablePromise<$models.SettingsDTO | null>}
 */
export function GetSettings() {
    return $Call.ByID(1747876599).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType55($result);
    }));
}

/**
 * GetSignature returns the configured email signature
 * @returns {$CancellablePromise<string>}
 */
export function GetSignature() {
    return $Call.ByID(3188673432);
}

/**
 * GetTaskCounts returns task count statistics
 * @returns {$CancellablePromise<$models.TaskCountsDTO | null>}
 */
export function GetTaskCounts() {
    return $Call.ByID(1288856655).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType57($result);
    }));
}

/**
 * GetTasks returns all tasks for the current account
 * @returns {$CancellablePromise<$models.TaskDTO[]>}
 */
export function GetTasks() {
    return $Call.ByID(1044052580).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * GetThread returns a complete thread with all messages for a given email ID
 * @param {number} emailID
 * @returns {$CancellablePromise<$models.ThreadDTO | null>}
 */
export function GetThread(emailID) {
    return $Call.ByID(581564166, emailID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType59($result);
    }));
}

/**
 * GetThreadByID returns a thread by its thread_id
 * @param {string} threadID
 * @returns {$CancellablePromise<$models.ThreadDTO | null>}
 */
export function GetThreadByID(threadID) {
    return $Call.ByID(469461218, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType59($result);
    }));
}

/**
 * GetThreadMessageCount returns the number of messages in a thread for an email
 * @param {number} emailID
 * @returns {$CancellablePromise<number>}
 */
export function GetThreadMessageCount(emailID) {
    return $Call.ByID(16988372, emailID);
}

/**
 * GetThreadSummary returns thread metadata for inbox display
 * @param {string} threadID
 * @returns {$CancellablePromise<$models.ThreadSummaryDTO | null>}
 */
export function GetThreadSummary(threadID) {
    return $Call.ByID(865196578, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType61($result);
    }));
}

/**
 * GetTopContacts returns the most frequently contacted contacts
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ContactDTO[]>}
 */
export function GetTopContacts(limit) {
    return $Call.ByID(3356455424, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType63($result);
    }));
}

/**
 * GetTopSenders returns top email senders
 * @param {number} limit
 * @param {string} period
 * @returns {$CancellablePromise<$models.SenderStatsDTO[]>}
 */
export function GetTopSenders(limit, period) {
    return $Call.ByID(2389341989, limit, period).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType65($result);
    }));
}

/**
 * GetUpcomingCalendarEvents returns upcoming events
 * @param {number} limit
 * @returns {$CancellablePromise<$models.CalendarEventDTO[]>}
 */
export function GetUpcomingCalendarEvents(limit) {
    return $Call.ByID(2126735007, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * InvalidateSummary removes a cached summary
 * @param {number} emailID
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateSummary(emailID) {
    return $Call.ByID(960315745, emailID);
}

/**
 * IsBasecampConnected returns true if Basecamp is connected
 * @returns {$CancellablePromise<boolean>}
 */
export function IsBasecampConnected() {
    return $Call.ByID(360931401);
}

/**
 * IsConnected returns true if connected to email server
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConnected() {
    return $Call.ByID(1404627993);
}

/**
 * IsGoogleCalendarConnected returns true if Google Calendar is connected
 * @returns {$CancellablePromise<boolean>}
 */
export function IsGoogleCalendarConnected() {
    return $Call.ByID(3850649934);
}

/**
 * IsReady returns true if the application is ready to use
 * @returns {$CancellablePromise<boolean>}
 */
export function IsReady() {
    return $Call.ByID(384760449);
}

/**
 * ListDrafts returns all drafts
 * @returns {$CancellablePromise<$models.DraftDTO[]>}
 */
export function ListDrafts() {
    return $Call.ByID(3792831158).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType66($result);
    }));
}

/**
 * ListGoogleCalendars returns all Google Calendars for the user
 * @returns {$CancellablePromise<$models.GoogleCalendarDTO[]>}
 */
export function ListGoogleCalendars() {
    return $Call.ByID(3757057984).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType68($result);
    }));
}

/**
 * MarkAsRead marks an email as read or unread
 * @param {number} id
 * @param {boolean} read
 * @returns {$CancellablePromise<void>}
 */
export function MarkAsRead(id, read) {
    return $Call.ByID(1482444775, id, read);
}

/**
 * MarkAsStarred marks an email as starred or unstarred
 * @param {number} id
 * @param {boolean} starred
 * @returns {$CancellablePromise<void>}
 */
export function MarkAsStarred(id, starred) {
    return $Call.ByID(4225286598, id, starred);
}

/**
 * MarkThreadAsRead marks all messages in a thread as read
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function MarkThreadAsRead(threadID) {
    return $Call.ByID(86703687, threadID);
}

/**
 * MarkThreadAsUnread marks the most recent message in a thread as unread
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function MarkThreadAsUnread(threadID) {
    return $Call.ByID(2571478696, threadID);
}

/**
 * MoveToFolder moves an email to a different folder
 * @param {number} id
 * @param {string} folder
 * @returns {$CancellablePromise<void>}
 */
export function MoveToFolder(id, folder) {
    return $Call.ByID(1365508830, id, folder);
}

/**
 * NeedsOAuth2Auth returns true if OAuth2 authentication is required
 * @returns {$CancellablePromise<boolean>}
 */
export function NeedsOAuth2Auth() {
    return $Call.ByID(335203554);
}

/**
 * NeedsSetup returns true if no account is configured
 * @returns {$CancellablePromise<boolean>}
 */
export function NeedsSetup() {
    return $Call.ByID(1486177408);
}

/**
 * OpenAttachment downloads attachment to temp and opens with default app
 * @param {number} attachmentID
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function OpenAttachment(attachmentID, filename) {
    return $Call.ByID(3146337491, attachmentID, filename);
}

/**
 * OpenAttachmentByPart downloads attachment by email ID + part number and opens with default app
 * @param {number} emailID
 * @param {string} partNumber
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function OpenAttachmentByPart(emailID, partNumber, filename) {
    return $Call.ByID(2164088583, emailID, partNumber, filename);
}

/**
 * OpenURL opens a URL in the default browser
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(1562308327, url);
}

/**
 * PostBasecampMessage posts a new message to a project
 * @param {number} projectID
 * @param {string} subject
 * @param {string} content
 * @returns {$CancellablePromise<$models.BasecampMessageDTO | null>}
 */
export function PostBasecampMessage(projectID, subject, content) {
    return $Call.ByID(3842834971, projectID, subject, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType69($result);
    }));
}

/**
 * Redo redoes the last undone operation
 * @returns {$CancellablePromise<$models.UndoResult>}
 */
export function Redo() {
    return $Call.ByID(3180465014).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType70($result);
    }));
}

/**
 * SaveAttachment saves an attachment to a file
 * @param {number} attachmentID
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveAttachment(attachmentID, path) {
    return $Call.ByID(3790155390, attachmentID, path);
}

/**
 * SaveAttachmentByPart downloads attachment by email ID + part number and saves to user-selected location
 * @param {number} emailID
 * @param {string} partNumber
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function SaveAttachmentByPart(emailID, partNumber, filename) {
    return $Call.ByID(279456426, emailID, partNumber, filename);
}

/**
 * SaveAttachmentDialog opens a file dialog and saves attachment to selected location
 * @param {number} attachmentID
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function SaveAttachmentDialog(attachmentID, filename) {
    return $Call.ByID(2331713166, attachmentID, filename);
}

/**
 * SaveBasecampConfig saves Basecamp configuration
 * @param {$models.BasecampConfigDTO} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveBasecampConfig(cfg) {
    return $Call.ByID(147010373, cfg);
}

/**
 * SaveDraft saves a draft email
 * @param {$models.DraftDTO} draft
 * @returns {$CancellablePromise<number>}
 */
export function SaveDraft(draft) {
    return $Call.ByID(2646402430, draft);
}

/**
 * SaveSettings saves all application settings
 * @param {$models.SettingsDTO} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(3588901310, settings);
}

/**
 * Search performs a full-text search
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.SearchResultDTO | null>}
 */
export function Search(query, limit) {
    return $Call.ByID(1458707606, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType72($result);
    }));
}

/**
 * SearchContacts searches for contacts by name or email
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ContactDTO[]>}
 */
export function SearchContacts(query, limit) {
    return $Call.ByID(3131711871, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType63($result);
    }));
}

/**
 * SearchInFolder searches within a specific folder
 * @param {string} folder
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.SearchResultDTO | null>}
 */
export function SearchInFolder(folder, query, limit) {
    return $Call.ByID(3842393593, folder, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType72($result);
    }));
}

/**
 * SelectBasecampAccount selects a Basecamp account and connects
 * @param {number} accountID
 * @returns {$CancellablePromise<void>}
 */
export function SelectBasecampAccount(accountID) {
    return $Call.ByID(1197316273, accountID);
}

/**
 * SelectFolder selects a folder as current
 * @param {string} name
 * @returns {$CancellablePromise<$models.FolderDTO | null>}
 */
export function SelectFolder(name) {
    return $Call.ByID(2451764766, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType73($result);
    }));
}

/**
 * SendDraft sends a draft
 * @param {number} id
 * @returns {$CancellablePromise<$models.SendResult | null>}
 */
export function SendDraft(id) {
    return $Call.ByID(151555103, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType75($result);
    }));
}

/**
 * SendEmail sends an email
 * @param {$models.SendRequest} req
 * @returns {$CancellablePromise<$models.SendResult | null>}
 */
export function SendEmail(req) {
    return $Call.ByID(1573461348, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType75($result);
    }));
}

/**
 * SetApplication stores the Wails app reference for events/dialogs
 * @param {application$0.App | null} wailsApp
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(wailsApp) {
    return $Call.ByID(3015383556, wailsApp);
}

/**
 * ShowError displays an error dialog
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowError(title, message) {
    return $Call.ByID(3606011075, title, message);
}

/**
 * ShowInfo displays an info dialog
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowInfo(title, message) {
    return $Call.ByID(209362495, title, message);
}

/**
 * Shutdown is called when the app terminates
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1827281352);
}

/**
 * StartOAuth2Auth initiates the OAuth2 authentication flow
 * Opens browser for user to authenticate and waits for callback
 * @returns {$CancellablePromise<void>}
 */
export function StartOAuth2Auth() {
    return $Call.ByID(3874937183);
}

/**
 * SummarizeEmail summarizes a single email using AI
 * @param {number} emailID
 * @returns {$CancellablePromise<string>}
 */
export function SummarizeEmail(emailID) {
    return $Call.ByID(4115574629, emailID);
}

/**
 * SummarizeEmailWithStyle summarizes an email with a specific style (tldr, brief, detailed)
 * @param {number} emailID
 * @param {string} style
 * @returns {$CancellablePromise<$models.SummaryResult | null>}
 */
export function SummarizeEmailWithStyle(emailID, style) {
    return $Call.ByID(3018231354, emailID, style).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * SummarizeThread summarizes an entire email thread using AI
 * @param {number} emailID
 * @returns {$CancellablePromise<string>}
 */
export function SummarizeThread(emailID) {
    return $Call.ByID(3907873783, emailID);
}

/**
 * SummarizeThreadDetailed returns detailed thread summary with structured data
 * @param {number} emailID
 * @returns {$CancellablePromise<$models.ThreadSummaryResult | null>}
 */
export function SummarizeThreadDetailed(emailID) {
    return $Call.ByID(1441776279, emailID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType77($result);
    }));
}

/**
 * SwitchToTerminal opens the TUI version in a terminal
 * @returns {$CancellablePromise<void>}
 */
export function SwitchToTerminal() {
    return $Call.ByID(1094240575);
}

/**
 * SyncContacts syncs contacts from Gmail
 * @param {boolean} fullSync
 * @returns {$CancellablePromise<void>}
 */
export function SyncContacts(fullSync) {
    return $Call.ByID(2899018368, fullSync);
}

/**
 * SyncCurrentFolder syncs the currently selected folder
 * @returns {$CancellablePromise<$models.SyncResultDTO | null>}
 */
export function SyncCurrentFolder() {
    return $Call.ByID(1068637202).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType79($result);
    }));
}

/**
 * SyncEssentialFolders syncs essential folders (INBOX, Sent, Trash) and purges deleted
 * @returns {$CancellablePromise<$models.SyncResultDTO[]>}
 */
export function SyncEssentialFolders() {
    return $Call.ByID(2942315924).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType80($result);
    }));
}

/**
 * SyncFolder syncs a specific folder and purges deleted emails
 * @param {string} folder
 * @returns {$CancellablePromise<$models.SyncResultDTO | null>}
 */
export function SyncFolder(folder) {
    return $Call.ByID(2354677997, folder).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType79($result);
    }));
}

/**
 * SyncFromGoogleCalendar syncs events from Google Calendar to local storage
 * @param {string} calendarID
 * @returns {$CancellablePromise<number>}
 */
export function SyncFromGoogleCalendar(calendarID) {
    return $Call.ByID(4017835720, calendarID);
}

/**
 * SyncTasksToCalendar syncs all tasks with due dates to calendar
 * @returns {$CancellablePromise<void>}
 */
export function SyncTasksToCalendar() {
    return $Call.ByID(106643106);
}

/**
 * SyncThreadsFromGmail syncs thread IDs from Gmail API
 * This is more accurate than local thread detection
 * @returns {$CancellablePromise<number>}
 */
export function SyncThreadsFromGmail() {
    return $Call.ByID(150569144);
}

/**
 * ToggleCalendarEventComplete toggles the completed status of an event
 * @param {number} id
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleCalendarEventComplete(id) {
    return $Call.ByID(1213055727, id);
}

/**
 * ToggleTaskComplete toggles the completed status of a task
 * @param {number} id
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleTaskComplete(id) {
    return $Call.ByID(2970500128, id);
}

/**
 * UncompleteBasecampTodo marks a todo as not completed
 * @param {number} projectID
 * @param {number} todoID
 * @returns {$CancellablePromise<void>}
 */
export function UncompleteBasecampTodo(projectID, todoID) {
    return $Call.ByID(1188449922, projectID, todoID);
}

/**
 * Undo undoes the last operation
 * @returns {$CancellablePromise<$models.UndoResult>}
 */
export function Undo() {
    return $Call.ByID(2323895332).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType70($result);
    }));
}

/**
 * UpdateBasecampTodo updates an existing todo
 * @param {$models.BasecampTodoInputDTO} input
 * @returns {$CancellablePromise<$models.BasecampTodoDTO | null>}
 */
export function UpdateBasecampTodo(input) {
    return $Call.ByID(1753404739, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * UpdateCalendarEvent updates an existing calendar event
 * @param {$models.CalendarEventInputDTO} input
 * @returns {$CancellablePromise<$models.CalendarEventDTO | null>}
 */
export function UpdateCalendarEvent(input) {
    return $Call.ByID(2243255687, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * UpdateTask updates an existing task
 * @param {$models.TaskInputDTO} input
 * @returns {$CancellablePromise<$models.TaskDTO | null>}
 */
export function UpdateTask(input) {
    return $Call.ByID(2556675062, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.BasecampAccountDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.BasecampTodoDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.CalendarEventDTO.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.TaskDTO.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.AccountDTO.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.AnalyticsResultDTO.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $models.AnalyticsOverviewDTO.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = $models.AttachmentDTO.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.AvailableFolderDTO.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $models.BasecampConfigDTO.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $models.BasecampMessageDTO.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = $models.BasecampPersonDTO.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = $models.BasecampProjectDTO.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $models.BasecampTodoListDTO.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = $Create.Array($$createType2);
const $$createType33 = $models.SummaryResult.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = $models.CalendarEventCountsDTO.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = $Create.Array($$createType4);
const $$createType38 = $models.ConnectionStatus.createFrom;
const $$createType39 = $models.ContactSyncStatusDTO.createFrom;
const $$createType40 = $Create.Nullable($$createType39);
const $$createType41 = $Create.Nullable($$createType11);
const $$createType42 = $models.DraftDTO.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
const $$createType44 = $models.EmailDetailDTO.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = $models.EmailDTO.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
const $$createType48 = $Create.Array($$createType46);
const $$createType49 = $models.FolderDTO.createFrom;
const $$createType50 = $Create.Array($$createType49);
const $$createType51 = $models.GoogleEventDTO.createFrom;
const $$createType52 = $Create.Array($$createType51);
const $$createType53 = $Create.Array($$createType6);
const $$createType54 = $models.SettingsDTO.createFrom;
const $$createType55 = $Create.Nullable($$createType54);
const $$createType56 = $models.TaskCountsDTO.createFrom;
const $$createType57 = $Create.Nullable($$createType56);
const $$createType58 = $models.ThreadDTO.createFrom;
const $$createType59 = $Create.Nullable($$createType58);
const $$createType60 = $models.ThreadSummaryDTO.createFrom;
const $$createType61 = $Create.Nullable($$createType60);
const $$createType62 = $models.ContactDTO.createFrom;
const $$createType63 = $Create.Array($$createType62);
const $$createType64 = $models.SenderStatsDTO.createFrom;
const $$createType65 = $Create.Array($$createType64);
const $$createType66 = $Create.Array($$createType42);
const $$createType67 = $models.GoogleCalendarDTO.createFrom;
const $$createType68 = $Create.Array($$createType67);
const $$createType69 = $Create.Nullable($$createType24);
const $$createType70 = $models.UndoResult.createFrom;
const $$createType71 = $models.SearchResultDTO.createFrom;
const $$createType72 = $Create.Nullable($$createType71);
const $$createType73 = $Create.Nullable($$createType49);
const $$createType74 = $models.SendResult.createFrom;
const $$createType75 = $Create.Nullable($$createType74);
const $$createType76 = $models.ThreadSummaryResult.createFrom;
const $$createType77 = $Create.Nullable($$createType76);
const $$createType78 = $models.SyncResultDTO.createFrom;
const $$createType79 = $Create.Nullable($$createType78);
const $$createType80 = $Create.Array($$createType78);
