// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AccountDTO represents an email account
 */
export class AccountDTO {
    /**
     * Creates a new AccountDTO instance.
     * @param {Partial<AccountDTO>} [$$source = {}] - The source object to create the AccountDTO.
     */
    constructor($$source = {}) {
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountDTO(/** @type {Partial<AccountDTO>} */($$parsedSource));
    }
}

/**
 * AnalyticsOverviewDTO contains general email statistics
 */
export class AnalyticsOverviewDTO {
    /**
     * Creates a new AnalyticsOverviewDTO instance.
     * @param {Partial<AnalyticsOverviewDTO>} [$$source = {}] - The source object to create the AnalyticsOverviewDTO.
     */
    constructor($$source = {}) {
        if (!("totalEmails" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalEmails"] = 0;
        }
        if (!("unreadEmails" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadEmails"] = 0;
        }
        if (!("starredEmails" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["starredEmails"] = 0;
        }
        if (!("archivedEmails" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["archivedEmails"] = 0;
        }
        if (!("sentEmails" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sentEmails"] = 0;
        }
        if (!("draftCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["draftCount"] = 0;
        }
        if (!("storageUsedMb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["storageUsedMb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyticsOverviewDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AnalyticsOverviewDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalyticsOverviewDTO(/** @type {Partial<AnalyticsOverviewDTO>} */($$parsedSource));
    }
}

/**
 * AnalyticsResultDTO contains all analytics data
 */
export class AnalyticsResultDTO {
    /**
     * Creates a new AnalyticsResultDTO instance.
     * @param {Partial<AnalyticsResultDTO>} [$$source = {}] - The source object to create the AnalyticsResultDTO.
     */
    constructor($$source = {}) {
        if (!("overview" in $$source)) {
            /**
             * @member
             * @type {AnalyticsOverviewDTO}
             */
            this["overview"] = (new AnalyticsOverviewDTO());
        }
        if (!("topSenders" in $$source)) {
            /**
             * @member
             * @type {SenderStatsDTO[]}
             */
            this["topSenders"] = [];
        }
        if (!("trends" in $$source)) {
            /**
             * @member
             * @type {EmailTrendsDTO}
             */
            this["trends"] = (new EmailTrendsDTO());
        }
        if (!("responseTime" in $$source)) {
            /**
             * @member
             * @type {ResponseTimeStatsDTO}
             */
            this["responseTime"] = (new ResponseTimeStatsDTO());
        }
        if (!("period" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["period"] = "";
        }
        if (!("generatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["generatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyticsResultDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AnalyticsResultDTO}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("overview" in $$parsedSource) {
            $$parsedSource["overview"] = $$createField0_0($$parsedSource["overview"]);
        }
        if ("topSenders" in $$parsedSource) {
            $$parsedSource["topSenders"] = $$createField1_0($$parsedSource["topSenders"]);
        }
        if ("trends" in $$parsedSource) {
            $$parsedSource["trends"] = $$createField2_0($$parsedSource["trends"]);
        }
        if ("responseTime" in $$parsedSource) {
            $$parsedSource["responseTime"] = $$createField3_0($$parsedSource["responseTime"]);
        }
        return new AnalyticsResultDTO(/** @type {Partial<AnalyticsResultDTO>} */($$parsedSource));
    }
}

/**
 * AttachmentDTO represents an email attachment
 */
export class AttachmentDTO {
    /**
     * Creates a new AttachmentDTO instance.
     * @param {Partial<AttachmentDTO>} [$$source = {}] - The source object to create the AttachmentDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["contentId"] = undefined;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * base64 encoded for inline images
             * @member
             * @type {string | undefined}
             */
            this["data"] = undefined;
        }
        if (!("isInline" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isInline"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["partNumber"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AttachmentDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttachmentDTO(/** @type {Partial<AttachmentDTO>} */($$parsedSource));
    }
}

/**
 * AvailableFolderDTO represents a folder with its sync status
 */
export class AvailableFolderDTO {
    /**
     * Creates a new AvailableFolderDTO instance.
     * @param {Partial<AvailableFolderDTO>} [$$source = {}] - The source object to create the AvailableFolderDTO.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isSelected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isSelected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailableFolderDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AvailableFolderDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvailableFolderDTO(/** @type {Partial<AvailableFolderDTO>} */($$parsedSource));
    }
}

/**
 * BasecampAccountDTO represents a Basecamp account from auth
 */
export class BasecampAccountDTO {
    /**
     * Creates a new BasecampAccountDTO instance.
     * @param {Partial<BasecampAccountDTO>} [$$source = {}] - The source object to create the BasecampAccountDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("href" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["href"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasecampAccountDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BasecampAccountDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BasecampAccountDTO(/** @type {Partial<BasecampAccountDTO>} */($$parsedSource));
    }
}

/**
 * BasecampConfigDTO represents Basecamp configuration for the frontend
 */
export class BasecampConfigDTO {
    /**
     * Creates a new BasecampConfigDTO instance.
     * @param {Partial<BasecampConfigDTO>} [$$source = {}] - The source object to create the BasecampConfigDTO.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Masked for display
             * @member
             * @type {string | undefined}
             */
            this["clientSecret"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["accountId"] = undefined;
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasecampConfigDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BasecampConfigDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BasecampConfigDTO(/** @type {Partial<BasecampConfigDTO>} */($$parsedSource));
    }
}

/**
 * BasecampMessageDTO represents a Basecamp message
 */
export class BasecampMessageDTO {
    /**
     * Creates a new BasecampMessageDTO instance.
     * @param {Partial<BasecampMessageDTO>} [$$source = {}] - The source object to create the BasecampMessageDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["projectId"] = 0;
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BasecampPersonDTO | null | undefined}
             */
            this["creator"] = undefined;
        }
        if (!("commentsCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["commentsCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasecampMessageDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BasecampMessageDTO}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("creator" in $$parsedSource) {
            $$parsedSource["creator"] = $$createField4_0($$parsedSource["creator"]);
        }
        return new BasecampMessageDTO(/** @type {Partial<BasecampMessageDTO>} */($$parsedSource));
    }
}

/**
 * BasecampPersonDTO represents a Basecamp person/user
 */
export class BasecampPersonDTO {
    /**
     * Creates a new BasecampPersonDTO instance.
     * @param {Partial<BasecampPersonDTO>} [$$source = {}] - The source object to create the BasecampPersonDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("emailAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["emailAddress"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["avatarUrl"] = undefined;
        }
        if (!("admin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["admin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasecampPersonDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BasecampPersonDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BasecampPersonDTO(/** @type {Partial<BasecampPersonDTO>} */($$parsedSource));
    }
}

/**
 * BasecampProjectDTO represents a Basecamp project
 */
export class BasecampProjectDTO {
    /**
     * Creates a new BasecampProjectDTO instance.
     * @param {Partial<BasecampProjectDTO>} [$$source = {}] - The source object to create the BasecampProjectDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * active, archived, trashed
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasecampProjectDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BasecampProjectDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BasecampProjectDTO(/** @type {Partial<BasecampProjectDTO>} */($$parsedSource));
    }
}

/**
 * BasecampTodoDTO represents a Basecamp to-do item
 */
export class BasecampTodoDTO {
    /**
     * Creates a new BasecampTodoDTO instance.
     * @param {Partial<BasecampTodoDTO>} [$$source = {}] - The source object to create the BasecampTodoDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("todoListId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["todoListId"] = 0;
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["projectId"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["dueOn"] = undefined;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["completedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BasecampPersonDTO | null | undefined}
             */
            this["creator"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BasecampPersonDTO[] | undefined}
             */
            this["assignees"] = undefined;
        }
        if (!("commentsCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["commentsCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasecampTodoDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BasecampTodoDTO}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType6;
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("creator" in $$parsedSource) {
            $$parsedSource["creator"] = $$createField8_0($$parsedSource["creator"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField9_0($$parsedSource["assignees"]);
        }
        return new BasecampTodoDTO(/** @type {Partial<BasecampTodoDTO>} */($$parsedSource));
    }
}

/**
 * BasecampTodoInputDTO represents input for creating/updating a to-do
 */
export class BasecampTodoInputDTO {
    /**
     * Creates a new BasecampTodoInputDTO instance.
     * @param {Partial<BasecampTodoInputDTO>} [$$source = {}] - The source object to create the BasecampTodoInputDTO.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["id"] = undefined;
        }
        if (!("todoListId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["todoListId"] = 0;
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["projectId"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["dueDate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["assigneeIds"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasecampTodoInputDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BasecampTodoInputDTO}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assigneeIds" in $$parsedSource) {
            $$parsedSource["assigneeIds"] = $$createField6_0($$parsedSource["assigneeIds"]);
        }
        return new BasecampTodoInputDTO(/** @type {Partial<BasecampTodoInputDTO>} */($$parsedSource));
    }
}

/**
 * BasecampTodoListDTO represents a Basecamp to-do list
 */
export class BasecampTodoListDTO {
    /**
     * Creates a new BasecampTodoListDTO instance.
     * @param {Partial<BasecampTodoListDTO>} [$$source = {}] - The source object to create the BasecampTodoListDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["projectId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["completedRatio"] = undefined;
        }
        if (!("todosCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["todosCount"] = 0;
        }
        if (!("completedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completedCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasecampTodoListDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BasecampTodoListDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BasecampTodoListDTO(/** @type {Partial<BasecampTodoListDTO>} */($$parsedSource));
    }
}

/**
 * CalendarEventCountsDTO represents calendar event count statistics
 */
export class CalendarEventCountsDTO {
    /**
     * Creates a new CalendarEventCountsDTO instance.
     * @param {Partial<CalendarEventCountsDTO>} [$$source = {}] - The source object to create the CalendarEventCountsDTO.
     */
    constructor($$source = {}) {
        if (!("upcoming" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["upcoming"] = 0;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalendarEventCountsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalendarEventCountsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CalendarEventCountsDTO(/** @type {Partial<CalendarEventCountsDTO>} */($$parsedSource));
    }
}

/**
 * CalendarEventDTO represents a calendar event for the frontend
 */
export class CalendarEventDTO {
    /**
     * Creates a new CalendarEventDTO instance.
     * @param {Partial<CalendarEventDTO>} [$$source = {}] - The source object to create the CalendarEventDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("accountId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["accountId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("eventType" in $$source)) {
            /**
             * 'custom', 'task_deadline', 'email_followup', 'meeting'
             * @member
             * @type {string}
             */
            this["eventType"] = "";
        }
        if (!("startTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startTime"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["endTime"] = undefined;
        }
        if (!("allDay" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allDay"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["color"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["taskId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["emailId"] = undefined;
        }
        if (!("isCompleted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCompleted"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * 'manual', 'task_sync', 'ai_suggestion'
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["googleEventId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["googleCalendarId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["lastSyncedAt"] = undefined;
        }
        if (!("syncStatus" in $$source)) {
            /**
             * 'local', 'synced', 'pending_sync', 'conflict'
             * @member
             * @type {string}
             */
            this["syncStatus"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalendarEventDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalendarEventDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CalendarEventDTO(/** @type {Partial<CalendarEventDTO>} */($$parsedSource));
    }
}

/**
 * CalendarEventInputDTO represents input for creating/updating a calendar event
 */
export class CalendarEventInputDTO {
    /**
     * Creates a new CalendarEventInputDTO instance.
     * @param {Partial<CalendarEventInputDTO>} [$$source = {}] - The source object to create the CalendarEventInputDTO.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["id"] = undefined;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["eventType"] = undefined;
        }
        if (!("startTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startTime"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["endTime"] = undefined;
        }
        if (!("allDay" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allDay"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["color"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["taskId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["emailId"] = undefined;
        }
        if (!("isCompleted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCompleted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalendarEventInputDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalendarEventInputDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CalendarEventInputDTO(/** @type {Partial<CalendarEventInputDTO>} */($$parsedSource));
    }
}

/**
 * ConnectionStatus represents IMAP connection status
 */
export class ConnectionStatus {
    /**
     * Creates a new ConnectionStatus instance.
     * @param {Partial<ConnectionStatus>} [$$source = {}] - The source object to create the ConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("lastSync" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastSync"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatus(/** @type {Partial<ConnectionStatus>} */($$parsedSource));
    }
}

/**
 * ContactDTO represents a contact for the frontend
 */
export class ContactDTO {
    /**
     * Creates a new ContactDTO instance.
     * @param {Partial<ContactDTO>} [$$source = {}] - The source object to create the ContactDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["givenName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["familyName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["photoUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["photoPath"] = undefined;
        }
        if (!("isStarred" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStarred"] = false;
        }
        if (!("interactionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interactionCount"] = 0;
        }
        if (!("emails" in $$source)) {
            /**
             * @member
             * @type {ContactEmailDTO[]}
             */
            this["emails"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ContactPhoneDTO[] | undefined}
             */
            this["phones"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContactDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContactDTO}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType10;
        const $$createField9_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("emails" in $$parsedSource) {
            $$parsedSource["emails"] = $$createField8_0($$parsedSource["emails"]);
        }
        if ("phones" in $$parsedSource) {
            $$parsedSource["phones"] = $$createField9_0($$parsedSource["phones"]);
        }
        return new ContactDTO(/** @type {Partial<ContactDTO>} */($$parsedSource));
    }
}

/**
 * ContactEmailDTO represents an email address for a contact
 */
export class ContactEmailDTO {
    /**
     * Creates a new ContactEmailDTO instance.
     * @param {Partial<ContactEmailDTO>} [$$source = {}] - The source object to create the ContactEmailDTO.
     */
    constructor($$source = {}) {
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (!("isPrimary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPrimary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContactEmailDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContactEmailDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContactEmailDTO(/** @type {Partial<ContactEmailDTO>} */($$parsedSource));
    }
}

/**
 * ContactPhoneDTO represents a phone number for a contact
 */
export class ContactPhoneDTO {
    /**
     * Creates a new ContactPhoneDTO instance.
     * @param {Partial<ContactPhoneDTO>} [$$source = {}] - The source object to create the ContactPhoneDTO.
     */
    constructor($$source = {}) {
        if (!("phone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phone"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (!("isPrimary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPrimary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContactPhoneDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContactPhoneDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContactPhoneDTO(/** @type {Partial<ContactPhoneDTO>} */($$parsedSource));
    }
}

/**
 * ContactSyncStatusDTO represents contact sync status
 */
export class ContactSyncStatusDTO {
    /**
     * Creates a new ContactSyncStatusDTO instance.
     * @param {Partial<ContactSyncStatusDTO>} [$$source = {}] - The source object to create the ContactSyncStatusDTO.
     */
    constructor($$source = {}) {
        if (!("totalContacts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalContacts"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | undefined}
             */
            this["lastSync"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContactSyncStatusDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContactSyncStatusDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContactSyncStatusDTO(/** @type {Partial<ContactSyncStatusDTO>} */($$parsedSource));
    }
}

/**
 * DailyStatsDTO contains email count per day
 */
export class DailyStatsDTO {
    /**
     * Creates a new DailyStatsDTO instance.
     * @param {Partial<DailyStatsDTO>} [$$source = {}] - The source object to create the DailyStatsDTO.
     */
    constructor($$source = {}) {
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyStatsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DailyStatsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyStatsDTO(/** @type {Partial<DailyStatsDTO>} */($$parsedSource));
    }
}

/**
 * DraftDTO represents a draft email
 */
export class DraftDTO {
    /**
     * Creates a new DraftDTO instance.
     * @param {Partial<DraftDTO>} [$$source = {}] - The source object to create the DraftDTO.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["id"] = undefined;
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["to"] = [];
        }
        if (!("cc" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["cc"] = [];
        }
        if (!("bcc" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["bcc"] = [];
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("bodyHtml" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyHtml"] = "";
        }
        if (!("bodyText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyText"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["replyToId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DraftDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DraftDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType13;
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("to" in $$parsedSource) {
            $$parsedSource["to"] = $$createField1_0($$parsedSource["to"]);
        }
        if ("cc" in $$parsedSource) {
            $$parsedSource["cc"] = $$createField2_0($$parsedSource["cc"]);
        }
        if ("bcc" in $$parsedSource) {
            $$parsedSource["bcc"] = $$createField3_0($$parsedSource["bcc"]);
        }
        return new DraftDTO(/** @type {Partial<DraftDTO>} */($$parsedSource));
    }
}

/**
 * EmailDTO represents an email for the frontend
 */
export class EmailDTO {
    /**
     * Creates a new EmailDTO instance.
     * @param {Partial<EmailDTO>} [$$source = {}] - The source object to create the EmailDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uid"] = 0;
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("fromName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromName"] = "";
        }
        if (!("fromEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromEmail"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["date"] = null;
        }
        if (!("isRead" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRead"] = false;
        }
        if (!("isStarred" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStarred"] = false;
        }
        if (!("hasAttachments" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasAttachments"] = false;
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["threadId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Number of emails in thread (for grouped view)
             * @member
             * @type {number | undefined}
             */
            this["threadCount"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmailDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EmailDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmailDTO(/** @type {Partial<EmailDTO>} */($$parsedSource));
    }
}

/**
 * EmailDetailDTO represents full email details for the frontend
 */
export class EmailDetailDTO {
    /**
     * Creates a new EmailDetailDTO instance.
     * @param {Partial<EmailDetailDTO>} [$$source = {}] - The source object to create the EmailDetailDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uid"] = 0;
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("fromName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromName"] = "";
        }
        if (!("fromEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromEmail"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["date"] = null;
        }
        if (!("isRead" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRead"] = false;
        }
        if (!("isStarred" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStarred"] = false;
        }
        if (!("hasAttachments" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasAttachments"] = false;
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["threadId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Number of emails in thread (for grouped view)
             * @member
             * @type {number | undefined}
             */
            this["threadCount"] = undefined;
        }
        if (!("toAddresses" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toAddresses"] = "";
        }
        if (!("ccAddresses" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ccAddresses"] = "";
        }
        if (!("bodyText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyText"] = "";
        }
        if (!("bodyHtml" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyHtml"] = "";
        }
        if (!("attachments" in $$source)) {
            /**
             * @member
             * @type {AttachmentDTO[]}
             */
            this["attachments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmailDetailDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EmailDetailDTO}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField16_0($$parsedSource["attachments"]);
        }
        return new EmailDetailDTO(/** @type {Partial<EmailDetailDTO>} */($$parsedSource));
    }
}

/**
 * EmailTrendsDTO contains email volume trends
 */
export class EmailTrendsDTO {
    /**
     * Creates a new EmailTrendsDTO instance.
     * @param {Partial<EmailTrendsDTO>} [$$source = {}] - The source object to create the EmailTrendsDTO.
     */
    constructor($$source = {}) {
        if (!("daily" in $$source)) {
            /**
             * @member
             * @type {DailyStatsDTO[]}
             */
            this["daily"] = [];
        }
        if (!("hourly" in $$source)) {
            /**
             * @member
             * @type {HourlyStatsDTO[]}
             */
            this["hourly"] = [];
        }
        if (!("weekday" in $$source)) {
            /**
             * @member
             * @type {WeekdayStatsDTO[]}
             */
            this["weekday"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmailTrendsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EmailTrendsDTO}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType19;
        const $$createField2_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("daily" in $$parsedSource) {
            $$parsedSource["daily"] = $$createField0_0($$parsedSource["daily"]);
        }
        if ("hourly" in $$parsedSource) {
            $$parsedSource["hourly"] = $$createField1_0($$parsedSource["hourly"]);
        }
        if ("weekday" in $$parsedSource) {
            $$parsedSource["weekday"] = $$createField2_0($$parsedSource["weekday"]);
        }
        return new EmailTrendsDTO(/** @type {Partial<EmailTrendsDTO>} */($$parsedSource));
    }
}

/**
 * FolderDTO represents a mail folder for the frontend
 */
export class FolderDTO {
    /**
     * Creates a new FolderDTO instance.
     * @param {Partial<FolderDTO>} [$$source = {}] - The source object to create the FolderDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("totalMessages" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalMessages"] = 0;
        }
        if (!("unreadMessages" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadMessages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderDTO(/** @type {Partial<FolderDTO>} */($$parsedSource));
    }
}

/**
 * GoogleCalendarDTO represents a Google Calendar
 */
export class GoogleCalendarDTO {
    /**
     * Creates a new GoogleCalendarDTO instance.
     * @param {Partial<GoogleCalendarDTO>} [$$source = {}] - The source object to create the GoogleCalendarDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("primary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["primary"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["backgroundColor"] = undefined;
        }
        if (!("accessRole" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accessRole"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoogleCalendarDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GoogleCalendarDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoogleCalendarDTO(/** @type {Partial<GoogleCalendarDTO>} */($$parsedSource));
    }
}

/**
 * GoogleEventDTO represents a Google Calendar event
 */
export class GoogleEventDTO {
    /**
     * Creates a new GoogleEventDTO instance.
     * @param {Partial<GoogleEventDTO>} [$$source = {}] - The source object to create the GoogleEventDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("calendarId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["calendarId"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["location"] = undefined;
        }
        if (!("startTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startTime"] = null;
        }
        if (!("endTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["endTime"] = null;
        }
        if (!("allDay" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allDay"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * confirmed, tentative, cancelled
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["htmlLink"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["colorId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoogleEventDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GoogleEventDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoogleEventDTO(/** @type {Partial<GoogleEventDTO>} */($$parsedSource));
    }
}

/**
 * HourlyStatsDTO contains email count per hour
 */
export class HourlyStatsDTO {
    /**
     * Creates a new HourlyStatsDTO instance.
     * @param {Partial<HourlyStatsDTO>} [$$source = {}] - The source object to create the HourlyStatsDTO.
     */
    constructor($$source = {}) {
        if (!("hour" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hour"] = 0;
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HourlyStatsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HourlyStatsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HourlyStatsDTO(/** @type {Partial<HourlyStatsDTO>} */($$parsedSource));
    }
}

/**
 * ResponseTimeStatsDTO contains response time statistics
 */
export class ResponseTimeStatsDTO {
    /**
     * Creates a new ResponseTimeStatsDTO instance.
     * @param {Partial<ResponseTimeStatsDTO>} [$$source = {}] - The source object to create the ResponseTimeStatsDTO.
     */
    constructor($$source = {}) {
        if (!("avgResponseMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avgResponseMinutes"] = 0;
        }
        if (!("medianMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["medianMinutes"] = 0;
        }
        if (!("responseRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["responseRate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResponseTimeStatsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResponseTimeStatsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResponseTimeStatsDTO(/** @type {Partial<ResponseTimeStatsDTO>} */($$parsedSource));
    }
}

/**
 * SearchResultDTO represents a search result
 */
export class SearchResultDTO {
    /**
     * Creates a new SearchResultDTO instance.
     * @param {Partial<SearchResultDTO>} [$$source = {}] - The source object to create the SearchResultDTO.
     */
    constructor($$source = {}) {
        if (!("emails" in $$source)) {
            /**
             * @member
             * @type {EmailDTO[]}
             */
            this["emails"] = [];
        }
        if (!("totalCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalCount"] = 0;
        }
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResultDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResultDTO}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("emails" in $$parsedSource) {
            $$parsedSource["emails"] = $$createField0_0($$parsedSource["emails"]);
        }
        return new SearchResultDTO(/** @type {Partial<SearchResultDTO>} */($$parsedSource));
    }
}

/**
 * SendRequest represents an email to send
 */
export class SendRequest {
    /**
     * Creates a new SendRequest instance.
     * @param {Partial<SendRequest>} [$$source = {}] - The source object to create the SendRequest.
     */
    constructor($$source = {}) {
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["to"] = [];
        }
        if (!("cc" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["cc"] = [];
        }
        if (!("bcc" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["bcc"] = [];
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("isHtml" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isHtml"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["replyTo"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("to" in $$parsedSource) {
            $$parsedSource["to"] = $$createField0_0($$parsedSource["to"]);
        }
        if ("cc" in $$parsedSource) {
            $$parsedSource["cc"] = $$createField1_0($$parsedSource["cc"]);
        }
        if ("bcc" in $$parsedSource) {
            $$parsedSource["bcc"] = $$createField2_0($$parsedSource["bcc"]);
        }
        return new SendRequest(/** @type {Partial<SendRequest>} */($$parsedSource));
    }
}

/**
 * SendResult represents the result of sending an email
 */
export class SendResult {
    /**
     * Creates a new SendResult instance.
     * @param {Partial<SendResult>} [$$source = {}] - The source object to create the SendResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendResult(/** @type {Partial<SendResult>} */($$parsedSource));
    }
}

/**
 * SenderStatsDTO contains statistics for a sender
 */
export class SenderStatsDTO {
    /**
     * Creates a new SenderStatsDTO instance.
     * @param {Partial<SenderStatsDTO>} [$$source = {}] - The source object to create the SenderStatsDTO.
     */
    constructor($$source = {}) {
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("unreadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadCount"] = 0;
        }
        if (!("percentage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percentage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SenderStatsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SenderStatsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SenderStatsDTO(/** @type {Partial<SenderStatsDTO>} */($$parsedSource));
    }
}

/**
 * SettingsDTO contains all application settings
 */
export class SettingsDTO {
    /**
     * Creates a new SettingsDTO instance.
     * @param {Partial<SettingsDTO>} [$$source = {}] - The source object to create the SettingsDTO.
     */
    constructor($$source = {}) {
        if (!("syncFolders" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["syncFolders"] = [];
        }
        if (!("uiTheme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uiTheme"] = "";
        }
        if (!("uiShowPreview" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["uiShowPreview"] = false;
        }
        if (!("uiPageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uiPageSize"] = 0;
        }
        if (!("composeFormat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["composeFormat"] = "";
        }
        if (!("composeSendDelay" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["composeSendDelay"] = 0;
        }
        if (!("syncInterval" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["syncInterval"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsDTO}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("syncFolders" in $$parsedSource) {
            $$parsedSource["syncFolders"] = $$createField0_0($$parsedSource["syncFolders"]);
        }
        return new SettingsDTO(/** @type {Partial<SettingsDTO>} */($$parsedSource));
    }
}

/**
 * SummaryResult represents an AI summary with metadata
 */
export class SummaryResult {
    /**
     * Creates a new SummaryResult instance.
     * @param {Partial<SummaryResult>} [$$source = {}] - The source object to create the SummaryResult.
     */
    constructor($$source = {}) {
        if (!("emailId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["emailId"] = 0;
        }
        if (!("style" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["style"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("keyPoints" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keyPoints"] = [];
        }
        if (!("cached" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cached"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SummaryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SummaryResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyPoints" in $$parsedSource) {
            $$parsedSource["keyPoints"] = $$createField3_0($$parsedSource["keyPoints"]);
        }
        return new SummaryResult(/** @type {Partial<SummaryResult>} */($$parsedSource));
    }
}

/**
 * SyncResultDTO represents the result of a sync operation
 */
export class SyncResultDTO {
    /**
     * Creates a new SyncResultDTO instance.
     * @param {Partial<SyncResultDTO>} [$$source = {}] - The source object to create the SyncResultDTO.
     */
    constructor($$source = {}) {
        if (!("newEmails" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newEmails"] = 0;
        }
        if (!("deletedEmails" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deletedEmails"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResultDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncResultDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncResultDTO(/** @type {Partial<SyncResultDTO>} */($$parsedSource));
    }
}

/**
 * TaskCountsDTO represents task count statistics
 */
export class TaskCountsDTO {
    /**
     * Creates a new TaskCountsDTO instance.
     * @param {Partial<TaskCountsDTO>} [$$source = {}] - The source object to create the TaskCountsDTO.
     */
    constructor($$source = {}) {
        if (!("pending" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending"] = 0;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskCountsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskCountsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskCountsDTO(/** @type {Partial<TaskCountsDTO>} */($$parsedSource));
    }
}

/**
 * TaskDTO represents a task for the frontend
 */
export class TaskDTO {
    /**
     * Creates a new TaskDTO instance.
     * @param {Partial<TaskDTO>} [$$source = {}] - The source object to create the TaskDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("accountId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["accountId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("isCompleted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCompleted"] = false;
        }
        if (!("priority" in $$source)) {
            /**
             * 0=normal, 1=high, 2=urgent
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["dueDate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["emailId"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * 'manual' or 'ai_suggestion'
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskDTO(/** @type {Partial<TaskDTO>} */($$parsedSource));
    }
}

/**
 * TaskInputDTO represents input for creating/updating a task
 */
export class TaskInputDTO {
    /**
     * Creates a new TaskInputDTO instance.
     * @param {Partial<TaskInputDTO>} [$$source = {}] - The source object to create the TaskInputDTO.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["id"] = undefined;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("isCompleted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCompleted"] = false;
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["dueDate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["emailId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskInputDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskInputDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskInputDTO(/** @type {Partial<TaskInputDTO>} */($$parsedSource));
    }
}

/**
 * ThreadDTO represents a thread with all messages
 */
export class ThreadDTO {
    /**
     * Creates a new ThreadDTO instance.
     * @param {Partial<ThreadDTO>} [$$source = {}] - The source object to create the ThreadDTO.
     */
    constructor($$source = {}) {
        if (!("threadId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["threadId"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("participants" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["participants"] = [];
        }
        if (!("messageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["messageCount"] = 0;
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {ThreadEmailDTO[]}
             */
            this["messages"] = [];
        }
        if (!("isRead" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRead"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreadDTO}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType13;
        const $$createField4_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("participants" in $$parsedSource) {
            $$parsedSource["participants"] = $$createField2_0($$parsedSource["participants"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField4_0($$parsedSource["messages"]);
        }
        return new ThreadDTO(/** @type {Partial<ThreadDTO>} */($$parsedSource));
    }
}

/**
 * ThreadEmailDTO represents a single email in a thread
 */
export class ThreadEmailDTO {
    /**
     * Creates a new ThreadEmailDTO instance.
     * @param {Partial<ThreadEmailDTO>} [$$source = {}] - The source object to create the ThreadEmailDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uid"] = 0;
        }
        if (!("messageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("fromName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromName"] = "";
        }
        if (!("fromEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromEmail"] = "";
        }
        if (!("toAddresses" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toAddresses"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["date"] = null;
        }
        if (!("isRead" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRead"] = false;
        }
        if (!("isStarred" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStarred"] = false;
        }
        if (!("isReplied" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isReplied"] = false;
        }
        if (!("hasAttachments" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasAttachments"] = false;
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (!("bodyText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyText"] = "";
        }
        if (!("bodyHtml" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyHtml"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadEmailDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreadEmailDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadEmailDTO(/** @type {Partial<ThreadEmailDTO>} */($$parsedSource));
    }
}

/**
 * ThreadSummaryDTO represents thread metadata for inbox display
 */
export class ThreadSummaryDTO {
    /**
     * Creates a new ThreadSummaryDTO instance.
     * @param {Partial<ThreadSummaryDTO>} [$$source = {}] - The source object to create the ThreadSummaryDTO.
     */
    constructor($$source = {}) {
        if (!("threadId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["threadId"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("lastSender" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSender"] = "";
        }
        if (!("lastSenderEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSenderEmail"] = "";
        }
        if (!("lastDate" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastDate"] = null;
        }
        if (!("messageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["messageCount"] = 0;
        }
        if (!("unreadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadCount"] = 0;
        }
        if (!("hasAttachments" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasAttachments"] = false;
        }
        if (!("participants" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["participants"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadSummaryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreadSummaryDTO}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("participants" in $$parsedSource) {
            $$parsedSource["participants"] = $$createField8_0($$parsedSource["participants"]);
        }
        return new ThreadSummaryDTO(/** @type {Partial<ThreadSummaryDTO>} */($$parsedSource));
    }
}

/**
 * ThreadSummaryResult represents a detailed thread summary
 */
export class ThreadSummaryResult {
    /**
     * Creates a new ThreadSummaryResult instance.
     * @param {Partial<ThreadSummaryResult>} [$$source = {}] - The source object to create the ThreadSummaryResult.
     */
    constructor($$source = {}) {
        if (!("threadId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["threadId"] = "";
        }
        if (!("participants" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["participants"] = [];
        }
        if (!("timeline" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timeline"] = "";
        }
        if (!("keyDecisions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keyDecisions"] = [];
        }
        if (!("actionItems" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["actionItems"] = [];
        }
        if (!("cached" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cached"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadSummaryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreadSummaryResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType13;
        const $$createField3_0 = $$createType13;
        const $$createField4_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("participants" in $$parsedSource) {
            $$parsedSource["participants"] = $$createField1_0($$parsedSource["participants"]);
        }
        if ("keyDecisions" in $$parsedSource) {
            $$parsedSource["keyDecisions"] = $$createField3_0($$parsedSource["keyDecisions"]);
        }
        if ("actionItems" in $$parsedSource) {
            $$parsedSource["actionItems"] = $$createField4_0($$parsedSource["actionItems"]);
        }
        return new ThreadSummaryResult(/** @type {Partial<ThreadSummaryResult>} */($$parsedSource));
    }
}

/**
 * UndoResult represents the result of an undo/redo operation
 */
export class UndoResult {
    /**
     * Creates a new UndoResult instance.
     * @param {Partial<UndoResult>} [$$source = {}] - The source object to create the UndoResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("canUndo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canUndo"] = false;
        }
        if (!("canRedo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canRedo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UndoResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UndoResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UndoResult(/** @type {Partial<UndoResult>} */($$parsedSource));
    }
}

/**
 * WeekdayStatsDTO contains email count per weekday
 */
export class WeekdayStatsDTO {
    /**
     * Creates a new WeekdayStatsDTO instance.
     * @param {Partial<WeekdayStatsDTO>} [$$source = {}] - The source object to create the WeekdayStatsDTO.
     */
    constructor($$source = {}) {
        if (!("weekday" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["weekday"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeekdayStatsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WeekdayStatsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeekdayStatsDTO(/** @type {Partial<WeekdayStatsDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AnalyticsOverviewDTO.createFrom;
const $$createType1 = SenderStatsDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = EmailTrendsDTO.createFrom;
const $$createType4 = ResponseTimeStatsDTO.createFrom;
const $$createType5 = BasecampPersonDTO.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType5);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = ContactEmailDTO.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = ContactPhoneDTO.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($Create.Any);
const $$createType14 = AttachmentDTO.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = DailyStatsDTO.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = HourlyStatsDTO.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = WeekdayStatsDTO.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = EmailDTO.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = ThreadEmailDTO.createFrom;
const $$createType25 = $Create.Array($$createType24);
